### ISSUE TITLE
关于一些使用问题

### ISSUE THREAD

**Issue by donneyluck** [Imymirror/imy-emacs.d#2]
看了大佬的 emacs 心得之路 觉得和自己很像
doom了很久 还是想自己配置一下
很喜欢您的配置  但是不知道怎么用  尤其是用了 meow以后  有些组合键和全局按键高不清楚了
大佬可以给个使用教程吗？
就常用的
1. 全局搜索文件 projectile-find-file
2. 全局搜索文本 rg
3. 当前文件搜索文本

KEYPAD模式下 不显示witch-key   都不知道触发什么命令  还望指点一下

**Comment by darkhandz** [comment]
啊，同楼上道友，我也想开始自己写配置，但是希望能配出基本能搜索文件名，grep项目里的文件内容，有space快捷键类似doom那样的

**Comment by KongZScott** [comment]
@donneyluck  @darkhandz 

> 想自己配置一下 给个使用教程吗？

我推荐 youtuber System Crafters 的视频，比如 从零配置系列 [Emacs From Scratch](https://www.youtube.com/playlist?list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ) 。这个家伙很贴心，有视频可以反复回看，而且视频与github code、文档一一映射，循序渐进，一定能学会。我能保证的是 System Crafters 老师的所有视频学习完毕，你基本上对如何配置 emacs 这件事情驾轻就熟了。新手一开始贵在找到一位老师，坚持学习下去。就像如果你学习 neovim，一开始我只推荐一位老师 youtuber Neil Sabde 。

> 用了 meow以后 有些组合键和全局按键高不清楚了

一旦尝试使用某一个模态，快捷键以及快捷键的组合总是要熟悉一段时间，直至达到肌肉记忆，才能发挥出其威力。知识勤学苦练达成技能，多种技能组合形成某件事情的胜任力。

**Comment by darkhandz** [comment]
> @donneyluck  @darkhandz 
> 
> 
> 
> > 想自己配置一下 给个使用教程吗？
> 
> 
> 
> 我推荐 youtuber System Crafters 的视频，比如 从零配置系列 [Emacs From Scratch](https://www.youtube.com/playlist?list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ) 。这个家伙很贴心，有视频可以反复回看，而且视频与github code、文档一一映射，循序渐进，一定能学会。我能保证的是 System Crafters 老师的所有视频学习完毕，你基本上对如何配置 emacs 这件事情驾轻就熟了。新手一开始贵在找到一位老师，坚持学习下去。就像如果你学习 neovim，一开始我只推荐一位老师 youtuber Neil Sabde 。
> 
> 
> 
> > 用了 meow以后 有些组合键和全局按键高不清楚了
> 
> 
> 
> 一旦尝试使用某一个模态，快捷键以及快捷键的组合总是要熟悉一段时间，直至达到肌肉记忆，才能发挥出其威力。知识勤学苦练达成技能，多种技能组合形成某件事情的胜任力。

请问你用了meow之后，会觉得比evil更方便轻松吗？

**Comment by donneyluck** [comment]
> > @donneyluck  @darkhandz 
> > 
> > 
> > 
> > > 想自己配置一下 给个使用教程吗？
> > 
> > 
> > 
> > 我推荐 youtuber System Crafters 的视频，比如 从零配置系列 [Emacs From Scratch](https://www.youtube.com/playlist?list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ) 。这个家伙很贴心，有视频可以反复回看，而且视频与github code、文档一一映射，循序渐进，一定能学会。我能保证的是 System Crafters 老师的所有视频学习完毕，你基本上对如何配置 emacs 这件事情驾轻就熟了。新手一开始贵在找到一位老师，坚持学习下去。就像如果你学习 neovim，一开始我只推荐一位老师 youtuber Neil Sabde 。
> > 
> > 
> > 
> > > 用了 meow以后 有些组合键和全局按键高不清楚了
> > 
> > 
> > 
> > 一旦尝试使用某一个模态，快捷键以及快捷键的组合总是要熟悉一段时间，直至达到肌肉记忆，才能发挥出其威力。知识勤学苦练达成技能，多种技能组合形成某件事情的胜任力。
> 
> 请问你用了meow之后，会觉得比evil更方便轻松吗？

我用回evil了

**Comment by donneyluck** [comment]
> 啊，同楼上道友，我也想开始自己写配置，但是希望能配出基本能搜索文件名，grep项目里的文件内容，有space快捷键类似doom那样的

我现在在用minemaca
配置很清晰 学习了一遍

**Comment by Imymirror** [comment]
> 请问你用了meow之后，会觉得比evil更方便轻松吗？

在二者都熟练的情况下， meow 相比 evil 的优势是 操作按键数量更少，package 更轻量。meow 的劣势是 只能在 emacs 上使用，而 vim 在各个 IDE、编辑器里几乎都有相应的插件支持。

我最近也用回 evil 了。因为我打算 emacs 、vim 双修。emacs 用来记笔记、任务管理。vim 用来在终端写代码。而 evil 能够让我在 vim 和 emacs 之间的编辑操作上统一，我不可能做到在两种不同哲学的模态之间自由切换。

emacs 我喜欢在 GUI 里操作，emacs 在终端经常遇到快捷键冲突或者不一样。vim 写代码我喜欢在终端，个人感觉写代码更流畅。

**Comment by darkhandz** [comment]
> > 请问你用了meow之后，会觉得比evil更方便轻松吗？
> 
> 在二者都熟练的情况下， meow 相比 evil 的优势是 操作按键数量更少，package 更轻量。meow 的劣势是 只能在 emacs 上使用，而 vim 在各个 IDE、编辑器里几乎都有相应的插件支持。
> 
> 我最近也用回 evil 了。因为我打算 emacs 、vim 双修。emacs 用来记笔记、任务管理。vim 用来在终端写代码。而 evil 能够让我在 vim 和 emacs 之间的编辑操作上统一，我不可能做到在两种不同哲学的模态之间自由切换。
> 
> emacs 我喜欢在 GUI 里操作，emacs 在终端经常遇到快捷键冲突或者不一样。vim 写代码我喜欢在终端，个人感觉写代码更流畅。

感谢分享，我用emacs做c项目的编辑器，看来还是没必要转meow。
neovim我用过lunarvim和nvchad，确实很快，但是没有doom-emacs那种开箱即用的【工作区】的配置（一个emacs frame可以同时开很多个项目的代码，相互间基本不干扰），很不习惯。
